use strum_macros::{Display, EnumString};

#[derive(Debug, Display, EnumString)]
pub enum Token {
    #[strum(to_string = "Identifier: {0}")]
    Identifier(String),
    #[strum(to_string = "Integer Constant: {0}")]
    IntegerConstant(i32),
    Int,
    Void,
    Return,
    OpenParenthesis,
    ClosedParenthesis,
    OpenBrace,
    ClosedBrace,
    Semicolon,
    Tilde,
    Hyphen,
    Plus,
    Asterisk,
    ForwardSlash,
    Percent,
    Ampersand,
    Pipe,
    Carrot,
    LeftShift,
    RightShift,
    Exclamation,
    DoubleAmpersand,
    DoublePipe,
    DoubleEqual,
    NotEqual,
    LessThan,
    GreaterThan,
    Leq,
    Geq,
    Equal,
    PlusEqual,
    MinusEqual,
    AsteriskEqual,
    ForwardSlashEqual,
    PercentEqual,
    AmpersandEqual,
    PipeEqual,
    CarrotEqual,
    LtLtEqual,
    GtGtEqual,
    DoubleHyphen,
    DoublePlus,
    If,
    Else,
    QuestionMark,
    Colon,
    Goto,
    Do,
    While,
    For,
    Break,
    Continue,
    Switch,
    Case,
    Default,
    Comma,
}
